<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.zouw</groupId>
        <artifactId>sante-soft</artifactId>
        <version>2.3.4.RELEASE</version>
    </parent>
    <artifactId>sante-soft-core</artifactId>
    <packaging>jar</packaging>
    <dependencies>
       
        <dependency>
            <groupId>com.base-frame.socle</groupId>
            <artifactId>base-frame-utils</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.base-frame.socle</groupId>
            <artifactId>base-frame-socle-core</artifactId>
            <version>1.0.0</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>com.base-frame.socle</groupId>
            <artifactId>base-frame-httpsession-security</artifactId>
            <version>1.0.0</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>com.base-frame.socle</groupId>
            <artifactId>base-frame-account-core</artifactId>
            <version>1.0.0</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>com.telesign</groupId>
            <artifactId>telesign</artifactId>
            <version>2.0.0</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>com.twilio.sdk</groupId>
            <artifactId>twilio</artifactId>
            <version>8.8.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.mashape.unirest</groupId>
            <artifactId>unirest-java</artifactId>
            <version>1.4.9</version>
        </dependency>
    </dependencies>
</project>