#spring.main.allow-bean-definition-overriding=true
## DataSource settings
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/achat4
#
#spring.datasource.tomcat.max-wait=30000
#spring.datasource.max-active=30000
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#hibernate.default_schema = "public"
#
##Location of the user image in the resource folder
#user.default.profile.image =static/img/profil.png
#
##spring.liquibase.default-schema = "socle_progiciel"
##liquibaseSchemaName: socle_progiciel
##datasource driver
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.naming.strategy=org.hibernate.cfg.ImprovedNamingStrategy
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#spring.liquibase.change-log=classpath:config/liquibase/master.xml
## Specify the DBMS
#spring.jpa.database= POSTGRESQL
#spring.application.name=syg
## Show or not log for each sql query
#spring.jpa.show-sql=false
#server.servlet.context-path=/achat-start-up
#
##Multipart files
#spring.servlet.multipart.max-file-size=100MB
#spring.servlet.multipart.max-request-size=200MB
##server.tomcat.basedir=${user.home}/deployer/tomcat
##dir.audio=${user.home}/audio/
#
#spring.jpa.hibernate.ddl-auto=none
#
## Naming strategy
#
#spring.jpa.show-sql = false
#security.sessions = ALWAYS
#server.port:8055
#spring.profiles.active: dev
## TRANSACTION (TransactionProperties)
## Default transaction timeout. If a duration suffix is not specified, seconds will be used.
#spring.transaction.default-timeout= 300
#spring.jpa.hibernate.connection.autocommit = false
#
#spring.jpa.hibernate.use-new-id-generator-mappings=true
#spring.jpa.open-in-view = true
#
#spring.messages.basename=i18n/messages
##spring.jpa.properties.hibernate.integration.envers.enabled=false
#
#spring.session.store-type=jdbc
#server.servlet.session.timeout= 5m
#spring.session.jdbc.initialize-schema=ALWAYS
#spring.session.jdbc.schema=classpath:org/springframework/session/jdbc/schema-@@platform@@.sql
#spring.session.jdbc.table-name=spring_session
#
#security.basic.enable=false
#security.basic.enabled=false
#management.security.enabled=false
#
#
#preview.cron.expression = 0 0 1 * * ?